-- Migração aditiva para o Pix do Mercado Pago via Orders API.
-- Aplicar uma vez no Supabase de produção após schema-pagamentos-caixa.sql.
begin;
alter table public.pedidos add column if not exists cliente_email text;
alter table public.pedidos add column if not exists pagamento_provedor text;
alter table public.pedidos add column if not exists pagamento_qr_code text;
alter table public.pedidos add column if not exists pagamento_qr_code_base64 text;
alter table public.pedidos add column if not exists pagamento_expira_em timestamptz;
alter table public.pedidos add column if not exists pagamento_idempotencia text;
create index if not exists pedidos_pagamento_provedor_idx on public.pedidos(pagamento_provedor);
create table if not exists public.pagamento_eventos (
  id bigint generated by default as identity primary key,
  provedor text not null,
  evento_id text not null,
  pagamento_id text not null,
  pedido_id text not null,
  status text not null,
  recebido_em timestamptz not null default now(),
  unique (provedor, evento_id),
  unique (provedor, pagamento_id, status)
);
alter table public.pagamento_eventos enable row level security;
revoke all privileges on table public.pagamento_eventos from public, anon, authenticated;
grant select, insert on table public.pagamento_eventos to service_role;
notify pgrst, 'reload schema';
commit;
